services:
  my-app:
    image: my-app:latest
    # ports: 
    #  - '8080:8080'
    networks:
      - backend 
      - monitoring
    depends_on: 
      - mongo   
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    # extra_hosts:
    #   - "my-app:8080"  
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password  
    volumes:
      - mongo_data:/data/db
    networks:
      - backend  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend  
networks:
  monitoring:
    driver: bridge
  backend:
    driver: bridge  
volumes:
  mongo_data: