events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://my-app:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # 🔥 ADD THIS LINE
            proxy_set_header Authorization $http_authorization;
        }
    }
}